# Generated by Django 4.2.7 on 2023-11-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_action_habits_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='дом', max_length=200, verbose_name='место')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(default='Разминка', max_length=200, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.place', verbose_name='место'),
        ),
    ]
