# Generated by Django 4.2.7 on 2023-11-30 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_place_alter_action_name_alter_habits_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 30, 13, 48, 32, 957510), verbose_name='время выполнения'),
        ),
    ]
