# Generated by Django 4.2.7 on 2023-11-30 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(default=datetime.time(13, 48, 57, 963335), verbose_name='время выполнения'),
        ),
    ]
