# Generated by Django 4.2.7 on 2023-11-30 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habits_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='time',
        ),
        migrations.AddField(
            model_name='habits',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 14, 56, 43, 967515), verbose_name='время выполнения'),
        ),
        migrations.AddField(
            model_name='habits',
            name='execution_time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='время на выполнение в минутах'),
        ),
        migrations.AddField(
            model_name='habits',
            name='is_pleasure',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
        migrations.AddField(
            model_name='habits',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='признак публичности'),
        ),
        migrations.AddField(
            model_name='habits',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='периодичность в днях'),
        ),
        migrations.AddField(
            model_name='habits',
            name='pleasure_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habits.habits', verbose_name='приятная привычка'),
        ),
        migrations.AddField(
            model_name='habits',
            name='reward',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение'),
        ),
    ]
