# Generated by Django 4.2.7 on 2023-11-30 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habits_time_habits_datetime_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 14, 59, 20, 508865), verbose_name='время выполнения'),
        ),
    ]
