# Generated by Django 4.2.7 on 2023-12-01 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habits_datetime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 19, 39, 35, 367155), verbose_name='время выполнения'),
        ),
    ]
