# Generated by Django 4.2.7 on 2023-12-01 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0008_alter_habits_datetime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habits.action', verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 19, 55, 9, 938829), verbose_name='время выполнения'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habits.place', verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
    ]
